server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail/loki/stuff/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

  - job_name: foo
    static_configs:
    - targets:
        - localhost
      labels:
        job: foo
        __path__: /tmp/promtail-loki/mylog/folder1/*

  - job_name: bar
    static_configs:
    - targets:
       - localhost
      labels:
       job: bar
       __path__: /tmp/promtail-loki/mylog/folder2/*
